service: uoy-app-course-search

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: eu-west-1
  memorySize: 1024
  environment:
    NODE_ENV: production
  tags:
    name: courses search
    group: ESG
    project: course-search
    status: ${env:DEPLOY_ENVIRONMENT, 'dev'}
    pushed_by: github
    defined_in: serverless
    repo_name: uoy-app-course-search
    team: "ESG Teaching and Learning"

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'
